# Generated by Django 6.0.4 on 2026-04-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория атауы')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='VolunteerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жоба атауы')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('location', models.CharField(max_length=100, verbose_name='Өтетін орны')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған күні')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Волонтерлік жоба',
                'verbose_name_plural': 'Волонтерлік жобалар',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100, verbose_name='Еріктінің аты')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон нөмірі')),
                ('message', models.TextField(verbose_name='Неліктен қатысқыңыз келеді?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.volunteerproject', verbose_name='Жоба')),
            ],
            options={
                'verbose_name': 'Өтінім',
                'verbose_name_plural': 'Өтінімдер',
            },
        ),
    ]
