# Generated by Django 6.0.4 on 2026-04-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerProject',
            new_name='Project',
        ),
    ]
